### ISSUE TITLE
multithreading issues on Raspberry Pi

### ISSUE THREAD

**Issue by mpsparrow** [mpsparrow/acarsdec#1] opened 2020-07-23 03:56 UTC
ACARS is a messaging system that aircraft use to communicate with the ground. The point of this code is to connect to an SDR (I'm using an RTL SDR) and decode the ACARS. The ACARS I am after broadcasts at a frequency range of roughly 129MHz to 132MHz. Each airline and region uses a slightly different frequency in that range to broadcast the ACARS messages. This program allows you to monitor up to 8 frequencies. Each frequency you monitor though is more load on the CPU.

It would appear the software is natively single-threaded. This is fine on my laptop as a single core is powerful enough to run the software while monitoring 8 frequencies. This is more an issue for low powered devices like a Raspberry Pi. I was able to monitor about 2 frequencies on the program before the single-threaded program maxed my core on my Raspberry Pi and the program stopped working properly. 

Ideally there would be a way to spread each frequency being monitored to a different thread so that it can more evenly distribute the load. There doesn't even need to be multithreading per-frequency being monitored as long as each frequency is running on different cores to allow for more frequencies to be monitored.

I don't know how hard it would be to do that as I am a C noob. It isn't a huge deal as I can use my laptop, although it would be cool if it was able to run well on the Raspberry Pi or lower powered devices. Don't waste your time though if you can't figure it out.

**Comment by ghost** [comment] 2020-07-24 14:25
I created a new branch that supports threading. Test the modifications and if everything works as intended just merge the linked pull request to close this issue automatically

**Closed as completed** 2020-07-24 18:20 UTC
Labels: enhancement
